- name: "Check python requirements"
  import_tasks: system/version.yml

- name: Install Ubuntu pre-requisites
  import_tasks: ubuntu/18.yml
  when: ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version == '18'