- name: "Creating config directory"
  file:
    path: "{{ var_data_path }}/config/service"
    state: directory
    recurse: yes
    owner: "{{ web.user }}"
    group: "{{ web.group }}"

- name: "Creating service file"
  template:
    src: systemd.j2
    dest: "{{ var_data_path }}/config/service/snitchdns.service"

- name: "Checking for installed service"
  stat:
    path: "/etc/systemd/system/snitchdns.service"
  register: existing_service

- name: "Creating link to service"
  when: existing_service.stat.exists == False
  file:
    src: "{{ var_data_path }}/config/service/snitchdns.service"
    dest: "/etc/systemd/system/snitchdns.service"
    state: link

- name: "Enabling and starting service"
  systemd:
    name: snitchdns
    daemon_reload: yes
    enabled: true
    state: started
