- name: "Install packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - python3-pip
      - python3-venv
      - acl
      - libpq-dev

- name: "Upgrade pip to latest and greatest version"
  pip:
    name: pip
    extra_args: --upgrade